version: "3"
services:
  redis-db:
    image: redis:alpine
    # set redis password
    command: redis-server --requirepass test124
    ports:
      - "6379:6379"
  consul:
    image: consul:latest
    hostname: "consul"
    ports:
      - "8500:8500"
    command: "agent -server -bootstrap-expect=1 -ui -client=0.0.0.0"
  token-service:
    build:
      context: ./tokenservice
    hostname: "token-service"
    ports:
      - "80:80"
    depends_on:
      - redis-db
    command:
      [
        "/app/bin/token",
        "--redis-host",
        "redis-db",
        "--redis-port",
        "6379",
        "--redis-password",
        "test124",
        "--redis-db",
        "0",
        "--server-port",
        "80",
        "--service-name",
        "token-service",
        "--consul-host",
        "consul",
        "--consul-port",
        "8500"
      ]

networks:
  micro-project:
    driver: bridge
